#include <iostream>
using namespace std;
#include "MyCrypto.h"


int main(int argc, char* argv[])
{
//    CodeCesar tmp;
////    tmp.chiffrage("Sylla exige que Cesar divorce de Cornelie Cinna et rompe ainsi ses derniers liens avec les marianistes. Cesar refuse, et doit se cacher, jusqu'a ce que de puissants protecteurs, dont son oncle Aurelius Cotta, fassent flechir Sylla et cesser la traque. Sylla lui a entretemps bloque sa nomination comme Flamen Dialis et les interdits qui l'accompagnaient. Prudent, Cesar quitte Rome. Il s'enrole dans l'armee et rejoint avec le preteur Marcus Minucius Thermus le theatre d'operations militaires en Asie, ou Lucullus assiege Mytilene, capitale de Lesbos qui s'etait ralliee a Mithridate VI. Cesar recoit mission de demander au roi de Bithynie Nicomede IV le renfort de sa flotte. Suetone se fait l'echo d'une rumeur sur la reputation de Cesar, rapportant qu'il aurait eu des relations sexuelles passives avec Nicomede, vice le plus meprisable aux yeux des Romains. Cette suspicion, qui peut  etre une lourde et classique plaisanterie entre soldats, plutot qu'une realite indemontrable, suivra Cesar, depuis les commentaires insultants  de ses adversaires jusqu'a son triomphe final.",3);
////    tmp.dechiffrage("VBOOD HALJH TXH FHVDU GLYRUFH GH FRUQHOLH FLQQD HW URPSH DLQVL VHV GHUQLHUV OLHQV DYHF OHV PDULDQLVWHV. FHVDU UHIXVH, HW GRLW VH FDFKHU, MXVTX'D FH TXH GH SXLVVDQWV SURWHFWHXUV, GRQW VRQ RQFOH DXUHOLXV FRWWD, IDVVHQW IOHFKLU VBOOD HW FHVVHU OD WUDTXH. VBOOD OXL D HQWUHWHPSV EORTXH VD QRPLQDWLRQ FRPPH IODPHQ GLDOLV HW OHV LQWHUGLWV TXL O'DFFRPSDJQDLHQW. SUXGHQW, FHVDU TXLWWH URPH. LO V'HQUROH GDQV O'DUPHH HW UHMRLQW DYHF OH SUHWHXU PDUFXV PLQXFLXV WKHUPXV OH WKHDWUH G'RSHUDWLRQV PLOLWDLUHV HQ DVLH, RX OXFXOOXV DVVLHJH PBWLOHQH, FDSLWDOH GH OHVERV TXL V'HWDLW UDOOLHH D PLWKULGDWH YL. FHVDU UHFRLW PLVVLRQ GH GHPDQGHU DX URL GH ELWKBQLH QLFRPHGH LY OH UHQIRUW GH VD IORWWH. VXHWRQH VH IDLW O'HFKR G'XQH UXPHXU VXU OD UHSXWDWLRQ GH FHVDU, UDSSRUWDQW TX'LO DXUDLW HX GHV UHODWLRQV VHAXHOOHV SDVVLYHV DYHF QLFRPHGH, YLFH OH SOXV PHSULVDEOH DXA BHXA GHV URPDLQV. FHWWH VXVSLFLRQ, TXL SHXW  HWUH XQH ORXUGH HW FODVVLTXH SODLVDQWHULH HQWUH VROGDWV, SOXWRW TX'XQH UHDOLWH LQGHPRQWUDEOH, VXLYUD FHVDU, GHSXLV OHV FRPPHQWDLUHV LQVXOWDQWV  GH VHV DGYHUVDLUHV MXVTX'D VRQ WULRPSKH ILQDO.",3);
////    tmp.cryptanalyse("VBOOD HALJH TXH FHVDU GLYRUFH GH FRUQHOLH FLQQD HW URPSH DLQVL VHV GHUQLHUV OLHQV DYHF OHV PDULDQLVWHV. FHVDU UHIXVH, HW GRLW VH FDFKHU, MXVTX'D FH TXH GH SXLVVDQWV SURWHFWHXUV, GRQW VRQ RQFOH DXUHOLXV FRWWD, IDVVHQW IOHFKLU VBOOD HW FHVVHU OD WUDTXH. VBOOD OXL D HQWUHWHPSV EORTXH VD QRPLQDWLRQ FRPPH IODPHQ GLDOLV HW OHV LQWHUGLWV TXL O'DFFRPSDJQDLHQW. SUXGHQW, FHVDU TXLWWH URPH. LO V'HQUROH GDQV O'DUPHH HW UHMRLQW DYHF OH SUHWHXU PDUFXV PLQXFLXV WKHUPXV OH WKHDWUH G'RSHUDWLRQV PLOLWDLUHV HQ DVLH, RX OXFXOOXV DVVLHJH PBWLOHQH, FDSLWDOH GH OHVERV TXL V'HWDLW UDOOLHH D PLWKULGDWH YL. FHVDU UHFRLW PLVVLRQ GH GHPDQGHU DX URL GH ELWKBQLH QLFRPHGH LY OH UHQIRUW GH VD IORWWH. VXHWRQH VH IDLW O'HFKR G'XQH UXPHXU VXU OD UHSXWDWLRQ GH FHVDU, UDSSRUWDQW TX'LO DXUDLW HX GHV UHODWLRQV VHAXHOOHV SDVVLYHV DYHF QLFRPHGH, YLFH OH SOXV PHSULVDEOH DXA BHXA GHV URPDLQV. FHWWH VXVSLFLRQ, TXL SHXW  HWUH XQH ORXUGH HW FODVVLTXH SODLVDQWHULH HQWUH VROGDWV, SOXWRW TX'XQH UHDOLWH LQGHPRQWUDEOH, VXLYUD FHVDU, GHSXLV OHV FRPPHQWDLUHV LQVXOWDQWV  GH VHV DGYHUVDLUHV MXVTX'D VRQ WULRPSKH ILQDO.");
//
//    Scytale tmp2;
////    tmp2.chiffrage("Une forme de transposition utilise le premier dispositif de cryptographie militaire connu, la scytale spartiate, remontant au Ve siecle avant JC. ", 3);
////    tmp2.dechiffrage("UPANOLESE I FTSOIPRFAM REDT EID AECT RETY,RP ATRNOESGMPROOANSPTIHATINIETO  NMA IUUL TIVITELA IISSRIEEE  CLCLEOE N PNARUVE,AM NILTEA R J SCDC.IY ST", 3);
////    tmp2.cryptanalyse("UPANOLESE I FTSOIPRFAM REDT EID AECT RETY,RP ATRNOESGMPROOANSPTIHATINIETO  NMA IUUL TIVITELA IISSRIEEE  CLCLEOE N PNARUVE,AM NILTEA R J SCDC.IY ST");
////    tmp2.chiffrage("J'aime les pommes mais surtout les fraises.",2);
//    //tmp2.dechiffrage("JS' ASIUMRETSO ULTE SL EPSO MFMREASI SMEASI.",2);
//    tmp2.cryptanalyse("JS' ASIUMRETSO ULTE SL EPSO MFMREASI SMEASI.");
//
//Vigenere tmp4;
//
////   Enigma tmp3;
////    tmp3.chiffrage("ALEXIS LE GUENNEC",0,5,0);
////    tmp3.dechiffrage("RUULMU VM HBVHUBI",0,5,0);
//
//
////    tmp4.chiffrage("plop","lol");
//      //  tmp4.dechiffrage("SAVWGWCHFWYRRGANRBLVRNNNWDRFUFBPBONXIEFWAENFABEE","MESDEUXVISAGESVEILLENTSURLESOUVERTURESDUTEMPSETDELESPACE");
//
//    //cout << tmp.getDecalage();

    QApplication app(argc, argv);
    MyCrypto mc;
    mc.show();
    return app.exec();

    return 0;
}


//FDSRSAEPEDRAFAOSTIATINRDAAEUIANCAILROTAQERMCSDITHNOSICOVUSTIYJETIOON

//CUITUKNLYIQWUILUYBBUDJIKHBUIEKLUHJKHUITKJUCFIUJTUBUIFQSU
//MESDEUXVISAGESVEILLENTSURLESOUVERTURESDUTEMPSETDELESPACE cesar 16

//SAVWGWCHFWYRRGANRBLVRNNNWDRFUFBPBONXIEFWAENFABEE
